unique_ids:
  assets:
    standard-page.html: IOUWV7AEVM3LSF5B5PPSSJLWKY7CT63L
    theme.css: PAM4WXWDNKOOK74NZHK5TZ4XYF7M4OWL
  forms:
    Form1: ZLZX7KBDIJ3AIUECQMYVFN6SINST2BXJ
  modules: {}
  scripts: {}
  server_modules: {}
